//go:build !ignore_autogenerated

/*
Copyright 2025 belgio99.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlavorRule) DeepCopyInto(out *FlavorRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlavorRule.
func (in *FlavorRule) DeepCopy() *FlavorRule {
	if in == nil {
		return nil
	}
	out := new(FlavorRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficSchedule) DeepCopyInto(out *TrafficSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficSchedule.
func (in *TrafficSchedule) DeepCopy() *TrafficSchedule {
	if in == nil {
		return nil
	}
	out := new(TrafficSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficScheduleList) DeepCopyInto(out *TrafficScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrafficSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficScheduleList.
func (in *TrafficScheduleList) DeepCopy() *TrafficScheduleList {
	if in == nil {
		return nil
	}
	out := new(TrafficScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficScheduleSpec) DeepCopyInto(out *TrafficScheduleSpec) {
	*out = *in
	if in.FlavorRules != nil {
		in, out := &in.FlavorRules, &out.FlavorRules
		*out = make([]FlavorRule, len(*in))
		copy(*out, *in)
	}
	in.ValidUntil.DeepCopyInto(&out.ValidUntil)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficScheduleSpec.
func (in *TrafficScheduleSpec) DeepCopy() *TrafficScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficScheduleStatus) DeepCopyInto(out *TrafficScheduleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficScheduleStatus.
func (in *TrafficScheduleStatus) DeepCopy() *TrafficScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficScheduleStatus)
	in.DeepCopyInto(out)
	return out
}
