FROM python:3.11-slim

WORKDIR /app

COPY common.py consumer.py common ./

RUN pip install --no-cache-dir aio-pika httpx kubernetes \
      prometheus-client fastapi uvicorn

EXPOSE 8001

CMD ["python", "consumer.py"]