FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn[standard] aio-pika httpx \
      python-dateutil prometheus-client kubernetes

COPY router.py ./
COPY common ./common/

EXPOSE 8000 8001

CMD ["python", "router.py"]