FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir aio-pika httpx kubernetes \
      prometheus-client fastapi uvicorn
      
COPY consumer.py ./
COPY common ./common/

EXPOSE 8000 8001

CMD ["python", "consumer.py"]