FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir aio-pika httpx kubernetes-asyncio \
      prometheus-client fastapi uvicorn uvloop httpx[http2]
      
COPY consumer.py ./
COPY common ./common/

EXPOSE 8000 8001

CMD ["python", "consumer.py"]